imports:
    - { resource: tables.yml }

services:
     lmdi.autolinks.listener:
        class: lmdi\autolinks\event\listener
        arguments:
            - '@dbal.conn'
            - '@config'
            - '@controller.helper'
            - '@template'
            - '@cache'
            - '@user'
            - '%lmdi.autolinks.tables.autolinks%'
        tags:
            - { name: event.listener }
